apiVersion: v1
kind: Pod
metadata:
  name: tahi-linux
spec:
  containers:
  - command:
    - sleep 
    - "36000"
    env:
    - name: DOCKER_HOST
      value: unix:///run/docker/docker.sock
    image: ansonnz/fluent-operator-development:1.0
    imagePullPolicy: IfNotPresent
    name: fluent-operator-development
    volumeMounts:
    - mountPath: /home/work/_work
      name: work
    - mountPath: /run/docker
      name: dind-sock
      readOnly: true
  - args:
    - dockerd
    - --host=unix:///run/docker/docker.sock
    - --group=$(DOCKER_GROUP_GID)
    env:
    - name: DOCKER_GROUP_GID
      value: "123"
    - name: DOCKER_IPTABLES_LEGACY
      value: "1"
    image: docker:dind
    imagePullPolicy: IfNotPresent
    name: dind
    securityContext:
      privileged: true
    volumeMounts:
    - mountPath: /home/work/_work
      name: work
    - mountPath: /run/docker
      name: dind-sock
    - mountPath: /home/work/externals
      name: dind-externals
  volumes:
  - emptyDir: {}
    name: work
  - emptyDir: {}
    name: dind-sock
  - emptyDir: {}
    name: dind-externals