apiVersion: v1
kind: Pod
metadata:
  name: tahi-linux-69r78-runner-s468z
  namespace: gh-runners
spec:
  containers:
  - command:
    - /home/runner/run.sh
    env:
    - name: DOCKER_HOST
      value: unix:///run/docker/docker.sock
    image: ghcr.io/t3i-tahi-bss/actions-runner:v2.324.0
    name: runner
    resources: {}
    volumeMounts:
    - mountPath: /home/runner/_work
      name: work
    - mountPath: /run/docker
      name: dind-sock
      readOnly: true
  - args:
    - dockerd
    - --host=unix:///run/docker/docker.sock
    - --group=$(DOCKER_GROUP_GID)
    - --default-network-opt=bridge=com.docker.network.driver.mtu=1450
    env:
    - name: DOCKER_GROUP_GID
      value: "123"
    - name: DOCKER_IPTABLES_LEGACY
      value: "1"
    image: docker:dind
    name: dind
    resources: {}
    securityContext:
      privileged: true
    volumeMounts:
    - mountPath: /home/runner/_work
      name: work
    - mountPath: /run/docker
      name: dind-sock
    - mountPath: /home/runner/externals
      name: dind-externals
  initContainers:
  - command:
    - cp
    - -r
    - -v
    - /home/runner/externals/.
    - /home/runner/tmpDir/
    image: ghcr.io/actions/actions-runner:latest
    name: init-dind-externals
    volumeMounts:
    - mountPath: /home/runner/tmpDir
      name: dind-externals
  volumes:
  - emptyDir: {}
    name: work
  - emptyDir: {}
    name: dind-sock
  - emptyDir: {}
    name: dind-externals